[package]
name = "photomosaic"
version = "0.1.0"
edition = "2024"

[dependencies]
rfd = "0.17.2"
eframe = "0.35.0"
wgpu = "29.0.3"
pollster = "0.4"
bytemuck = { version = "1.22.0", features = ["extern_crate_alloc"] }
image = "0.25.2"
serde_json = { version = "1.0.150", default-features = false, features = ["alloc"] }
serde = { version = "1.0.228", features = ["derive"] }
rand = "0.10.2"
chrono = "0.4.45"
#glib = { git = "https://github.com/Glasta326/glib-rust.git"}
